sd2001/HacktoberFest2020

Mail-with-Python/htmlMail.py
Mail-with-Python/index.html

Used python to send emails with external html file support.

Made a python script to send e-mails via gmail

---

Prathamesh Files/Main.java
Prathamesh Files/README.md
Prathamesh Files/perimeter.java

Files Added

---

Suvodeep's Files/FloydsTriangle.cpp
Suvodeep's Files/PascalsTraingle.cpp

i have added two cpp questions

Suvoo files added

---

sudoko_solver/sudoko_solver.cpp

input format:
0 for blank spaces
space after each input

program to solve 9x9 sudoko

---

Jayvardhan/date.py
Jayvardhan/experiment.py
Jayvardhan/working-mail.py

added python scripts

---

cp/.gitignore
cp/model/User.js
cp/package-lock.json
cp/package.json
cp/routes/auth.js
cp/routes/posts.js
cp/routes/verifyToken.js
cp/server.js
cp/validation.js

added middleware for authorization

added jwt auth middleware

---

tic-tac-toe.py

tic-tac-toe game

---

guessinggame.py

python guess the number game

---

Hacktoberfest2020/index.html

A pull request for a noob lol?

---

ArrayInReverseorder.cpp

code of arrayInreverse order in C++ is added
input=
4
1234
output= 4321

ArrayInrevrse

---

A - Frog 1.cxx
Frog 2.cxx
Knapsack1.cxx

My Cp Solutions

---

Tree_Traversal/Boundary_Traversal.cpp
Tree_Traversal/InOrder_Traversal.cpp
Tree_Traversal/PostOrder_Traversal.cpp
Tree_Traversal/PreOrder_Traversal.cpp
Tree_Traversal/Spiral_Traversal.cpp

This PR adds 5 tree traversals to the repo. Preorder, Inorder, PostOrder, Boundary, and Spiral Traversal.

Tree Traversals added

---

Moving Block Game/.gitignore
Moving Block Game/index.html
Moving Block Game/package-lock.json
Moving Block Game/package.json
Moving Block Game/scripts.js

This is a Board Game made using JS, HTML where boxes move without colliding with each other.
The basic Flow of the project is:-
1. The game loads and 2 blocks of different colors are displayed.
2. The User controls are written below the Canvas area.
3. Thus simply move the blocks they will not exit the area and will not collide.

Added basic block-game

---

Backtracking/Flood_Fill.cpp
Backtracking/Maze.cpp
Backtracking/N_Queens.cpp

Backtracking program files added

---

Web_Crawler/Books_scraper.py
Web_Crawler/Quotes_extractor.py
bin_search/Aggressive_Cows.cpp
bin_search/Book_Allocation.cpp

Two medium level difficulty problems from SPOJ added

Problems on binary Search added

---

Web_Crawler/Books_scraper.py
Web_Crawler/Quotes_extractor.py

Quotes scraper and Book scraper added

Web Scraping programs added

---

binarytree.c

Inorder preorder and postorder tree traversals in C programming

Tree traversals implemented in C language

---

vivek sharma/RockPaperScissor.py

hye,i am adding rock paper scissor game in python.

vivek sharma

---

Java Prog/noOfUpperCase.java

Added Java Folder and a program to find number of UpperCase in a string.

Added java program.

---

Multisource bfs/Codechef  -  Snakes and transition from Capitalism to Socialism.cpp
Multisource bfs/Codeforces  - Christmas Trees.cpp
Multisource bfs/Spoj - BITMAP - Bitmap.cpp

I have added a very famous algorithm that is derived from BFS, which is Multisource BFS. It contains three problems and their solutions from Codechef, Codeforces, and Spoj.

Multisource BFS Added

---

Algorithms/MergeSort.py

Merge sort is one of the most prominent divide-and-conquer sorting algorithms in the modern era. It can be used to sort the values in any traversable data structure such as a list.

Created a new folder for Algorithms and added Merge Sort Algorithm

---

Algorithms/first_n_primes.c

Print first N primes using Sieve of Eratosthenes. (Optimized Algorithm) .i.e. Time Complexity: O(log n)

Print first N primes using Sieve of Eratosthenes.

---

c program/Circular LinkedList.c
c program/Create A Basic Stack.c
c program/Create Queue Using LinkedList.c
c program/Doubly LinkedList.c
c program/LinkedList Add Consonants After Vowels.c

Programs include doubly/circular linked list, queue using linked list, stack, etc.

Added a few Data Structures programs in C

---

cpp files/Binary Search Iter.cpp
cpp files/Matrix Multiplication.cpp

Iterative binary search and matrix multiplication added

Added some C++ programs to CPP Files

---

Java Prog/PalindromicLinkedList.java

Added an efficient java program to find whether a linked list is Palindrome with the use of Stack.

Added Java Program for Palindromic Linked List

---

Algorithms/SelectionSort.py

Selection sort is an algorithm that selects the smallest element from an unsorted list in each iteration and places that element at the beginning of the unsorted list.
Here's how it works-
1. Set the first element as minimum.
2. Compare minimum with the second element. If the second element is smaller than minimum, assign the second element as minimum.
Compare minimum with the third element. Again, if the third element is smaller, then assign minimum to the third element otherwise do nothing. The process goes on until the last element.
3. After each iteration, minimum is placed in the front of the unsorted list.
4. For each iteration, indexing starts from the first unsorted element.
5. Step 1 to 3 are repeated until all the elements are placed at their correct positions.

Added selection sort algorithm to the Algorithm's folder.

---

Python/wordcount.py

1. Created a folder "Python" for all python code.
2. Added wordcount.py, the python scripts gives the frequency of words in a text file that the user enters.

Added wordcount.py

---

Searching-algo/binary-search.cpp
Searching-algo/exponential-search.cpp
Searching-algo/interpolation-search.cpp
Searching-algo/linear-search.cpp

Added few searching algorithms in cpp
1. Linear Search
2. Binary Search
3. Exponential Search
4.  Interpolation Search

Added Searching Algorithms in cpp

---

cpp files/mergeSort.cpp

Merge sort efficient implementation in O(nlogn) time complexity.

Added Merge sort implementation

---

cpp files/DLL.cpp
cpp files/SLL.cpp

Added Singly linked list and Doubly linked list with more inbuilt functionality than previously added code (in C++ language).

Added SLL and DLL in C++

---

Interview Based/Anagram.py
Interview Based/CamelCase Pattern Matching.py
Interview Based/Check if strings are rotations of each other or not.py
Interview Based/Chocolate Distribution Problem.py
Interview Based/Convert array into Zig-Zag fashion.py
Interview Based/Count the triplets.py
Interview Based/Element with left side smaller and right side greater.py
Interview Based/Equilibrium Point.py
Interview Based/Form a palindrome.py
Interview Based/Implement Atoi.py
Interview Based/Implement strstr.py
Interview Based/Inversion of array.py
Interview Based/Kadane's Algorithm.py
Interview Based/Kth smallest element.py
Interview Based/Largest Number formed from an Array.py
Interview Based/Last index of One.py
Interview Based/Leader_in_array.py
Interview Based/Repeated.py
Interview Based/Top 4.py
Interview Based/reverse.py

This is a contribution to the Hacktober Fest 2020. Please review the code and accept the PR.

Added Interview Based Directory and files to the Repo

---

.vscode/settings.json
Hackerrank Solution Snippets/Alphabet Rangoli.py
Hackerrank Solution Snippets/Alternating_Characters.py
Hackerrank Solution Snippets/Capitalize.py
Hackerrank Solution Snippets/Count_Triplets.py
Hackerrank Solution Snippets/Designer Door Mat.py
Hackerrank Solution Snippets/Find a string.py
Hackerrank Solution Snippets/Find the Runner-Up Score!.py
Hackerrank Solution Snippets/Finding the eprcentage.py
Hackerrank Solution Snippets/Introduction to Sets.py
Hackerrank Solution Snippets/Java 1D Array (Part 2).java
Hackerrank Solution Snippets/Java BigDecimal.java
Hackerrank Solution Snippets/Java Currency Formatter.java
Hackerrank Solution Snippets/Java Output Formatting.java
Hackerrank Solution Snippets/Java Regex 2 - Duplicate Words.java
Interview Based/Longest Palindrome in a String.py
Interview Based/Merge Without Extra Space.py
Interview Based/Minimum Platforms.py
Interview Based/Missing number in array.py
Interview Based/Most frequent word in an array of strings.py
Interview Based/Non Repeating Character.py
Interview Based/Number of pairs.py
Interview Based/Organiser.py
Interview Based/Pairs.py
Interview Based/Permutations of a given string.py
Interview Based/Rearrange Array Alternately.py

Added hackerrank solutions for contributing to Hacktoberfest 2020. Please review and accept the PR.

Add hackerrank solns

---

Interview Based/Longest Palindrome in a String.py
Interview Based/Merge Without Extra Space.py
Interview Based/Minimum Platforms.py
Interview Based/Missing number in array.py
Interview Based/Most frequent word in an array of strings.py
Interview Based/Non Repeating Character.py
Interview Based/Number of pairs.py
Interview Based/Organiser.py
Interview Based/Pairs.py
Interview Based/Permutations of a given string.py
Interview Based/Rearrange Array Alternately.py

Added few more Interview Based Solutions to the respective directory. Please review and accept the PR.

Yes hcktbr

---

ColorfulSpiral/spiral.py

Hey there!
Added a python script file inside ColorfulSpiral directory in callmebhawesh branch. This is a very nice script to run and it makes a beautiful round like spiral in terminal. I hope you'll like it. As i am a beginner so  i made this, i'll hope to contribute more in the future.
Regards,
github.com/callmebhawesh
screenshot:

A beautiful colorful spiral art made by python

---

ann-www/multiply.js

This PR is for Hacktoberfest 2020. Thanks! 🙂

Add multiply.js in ann-www diretory

---

ann-www/subtraction.js

This PR is for Hacktoberfest 2020. Thanks! 🙂

Add subtraction.js in ann-www diretory

---

ann-www/addition.js

This PR is for Hacktoberfest 2020. Thanks! 🙂

Add addition.js in ann-www diretory

---

ann-www/hello-world.js

This PR is for Hacktoberfest 2020. Thanks! 🙂

Create ann-www directory & add a new hello world program

---

RockPaperScissorsSpockLizard.py

A simple game of rock, paper, scissors in need of touch ups

Added a Python game

---

FormatMoney/FormatMoney.js

Format Money Javascript

---

hacktw/add.cpp

Follow @hacktw02's sample for hacktoberfest 2020. Thanks!

Add add.cpp in hacktw directory

---

hacktw/add.c

Follow @hacktw02's sample for hacktoberfest 2020. Thanks!

Add add.c in hacktw directory

---

hacktw/add.js

Follow @hacktw02's sample for hacktoberfest 2020. Thanks!

Add add.js in hacktw directory

---

hacktw/hello-world.c

PR for hacktoberfest 2020. Thank you. 👍

Add hello-world.c in hacktw dir 

---

hacktw/hello-world.cpp

PR for hacktoberfest 2020. Thank you. 👍

Add hello-world.cpp in hacktw dir

---

hacktw/hello-world.js

PR for hacktoberfest 2020. Thank you. 👍

Add hello-world.js in hacktw dir

---

hacktw/hello-world.py

PR for hacktoberfest 2020. Thank you. 👍

Add hello-world.py in hacktw dir

---

Vehicle Counting/VehicleCounter.py

A python program to count the number of vehicles passing. This pull request is for hacktober fest 2020.

Vehicle Counter

---

currencyconverter.py

This is a straightforward project with a simple GUI. The name quite evidently describes the role of the project is to convert currencies from one unit into another. For example, converting Indian rupee to USD or euro. Tkinter, the standard Python interface can be used to design and develop this application.

currencyconverter.py

---

Leetcode_solutions/141. Linked List Cycle/141. Linked List Cycle.java
Leetcode_solutions/141. Linked List Cycle/Readme.md
Leetcode_solutions/142. Linked List Cycle II/142.linked-list-ii.java
Leetcode_solutions/142. Linked List Cycle II/Readme.md
Leetcode_solutions/15. 3sum/15.3sum.java
Leetcode_solutions/15. 3sum/Readme.md
Leetcode_solutions/442. Find All Duplicates in an Array/442. Find All Duplicates in an Array.java
Leetcode_solutions/442. Find All Duplicates in an Array/Readme.md
Leetcode_solutions/83. Remove Duplicates from Sorted List/83. Remove Duplicates from Sorted List.java
Leetcode_solutions/83. Remove Duplicates from Sorted List/Readme.md

I have added a leetcode folder and 5 leetcode solutions to the repository! Hope this helps!

Added leetcode solutions

---

madlibsgenerator.py

This python beginner project is a good start for beginner software developers as it has concepts like strings, variables, and concatenation. Mad Libs Generator teaches to manipulate user-inputted data as the Mad Libs refer to a series of inputs that a user enters. The input from the user could be anything from an adjective, a pronoun, or even a verb. After all the inputs are entered the application takes all the data and arranges it to build a story template.

madlibsgenerator.py

---

Fruits Project/app.js
Fruits Project/package-lock.json
Fruits Project/package.json

This file/folder is forHacktoberFest 2020. Submitted by Siddhesh Shinde

Fruits Web App

---

Calculator/Calculator in C.c

calculator in c for addition, substraction, multiplication, printing N number.

Create Calculator in C.c
